name = "ruhira-store"
account_id = "605215095155e711897743a2259ee14a"
main = "worker.js"
compatibility_date = "2026-08-21"

[assets]
directory = "."
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "ruhira-db"
database_id = "0927be55-d52b-4ac9-8092-6c9d45929edc"
